import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../../api';

function timeAgo(dateString) {
  const now = new Date();
  const then = new Date(dateString);
  const diff = Math.floor((now - then) / 1000);
  if (diff < 60) return 'just now';
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  if (diff < 604800) return `${Math.floor(diff / 86400)}d ago`;
  return then.toLocaleDateString();
}

export default function News() {
  const [articles, setArticles] = useState([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    api.articles()
      .then(setArticles)
      .catch(() => setArticles([]))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="page-shell">
        <div className="page-header">
          <h1 className="page-title">News</h1>
          <p className="page-subtitle">Loading articles…</p>
        </div>
      </div>
    );
  }

  return (
    <div className="page-shell">
      <div className="page-header">
        <h1 className="page-title">News</h1>
        <p className="page-subtitle">
          AI-generated insights on emerging technology and environmental impact
        </p>
      </div>

      {articles.length === 0 ? (
        <div className="news-empty">
          <div className="news-empty-icon">◇</div>
          <h3>No articles yet</h3>
          <p>Articles will appear here once generated by an admin.</p>
        </div>
      ) : (
        <div className="news-grid">
          {articles.map((article) => (
            <article
              key={article.id}
              className="news-card"
            >
              <div className="news-card-header">
                <div className="news-card-meta">
                  <span className="news-timestamp">{timeAgo(article.generatedAt)}</span>
                  {article.tags?.length > 0 && (
                    <div className="news-tags">
                      {article.tags.map((tag) => (
                        <span key={tag} className="news-tag">{tag}</span>
                      ))}
                    </div>
                  )}
                </div>
                <h2 className="news-card-title">{article.title}</h2>
                <p className="news-card-summary">{article.summary}</p>
              </div>

              <button
                className="btn-secondary news-read-btn"
                onClick={() => navigate(`/news/${article.id}`)}
              >
                Read full article →
              </button>
            </article>
          ))}
        </div>
      )}
    </div>
  );
}
